on:
  push:
    branches:
      - develop

name: 'Test'
jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Clean install and run jest
        run: yarn install --frozen-lockfile
